language: ruby
sudo: false

services:
  - postgresql

before_install:
  - gem install bundler:1.17.1

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - cp config/database.travis.yml config/database.yml
  # We don't want to seed the database for tests
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
