# Install required roles with
# cd provisioning
# ansible-galaxy install -r requirements.yml -p roles

- src: newrelic.newrelic-infra
  version: 0.8.2

- src: rvm.ruby
  version: v2.1.0

- src: geerlingguy.certbot
  version: 3.0.0

- src: DavidWittman.redis
  version: 1.2.0

- src: ANXS.postgresql
  version: v1.0.3

- src: nickhammond.logrotate
  version: v0.0.5
